In [63]:
import numpy as np
from scipy.spatial.transform import Rotation

from math import cos, sin, sqrt, pi

Из всей библиотеки нам нужен только класс `Rotation` в котором определены методы для создания вращающего объекта. Создать такой объект можно разными способами, а после создания конвертировать из одного представления в другое.

In [81]:
# Создадим вращающий объект из последовательности элементарных матриц
R = Rotation.from_euler(seq='XYZ', angles=(90, 90, 90), degrees=True)

In [82]:
# Представим его также последовательностью элементарных матриц, но уже другой
R.as_euler(seq='XYX', degrees=True)

array([180.,  90.,   0.])

In [83]:
# Можно представить и просто в виде матрицы вращения
R.as_matrix()

array([[ 0.,  0.,  1.],
       [ 0., -1.,  0.],
       [ 1.,  0.,  0.]])

In [84]:
"Кватернион"
R.as_quat()

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [85]:
"вектор истинного эйлерова поворота или просто вектор поворота/вращения"
rv = R.as_rotvec() 
"Угол вращения — норма вектора поворота"
θ = np.rad2deg(np.linalg.norm(rv))
"Единичный направляющий вектор оси вращения можно получить, разделив на величину угла"
a = rv / θ
# распечатем значения переменных
print(f"{rv=},\n{θ=},\n{a=}")

rv=array([2.22144147, 0.        , 2.22144147]),
θ=180.00000000000003,
a=array([0.01234134, 0.        , 0.01234134])


In [35]:
"Угол вращения"
R.magnitude()

3.141592653589793

In [36]:
# Параметры Родрига–Гамильтона, вычисляются только λ_1, λ_2, λ_3
# λ_0 можно получить из условия нормировки (см. презентацию)"
R.as_mrp()

array([0.70710678, 0.        , 0.70710678])

In [47]:
# набор точек, которые хотим вращать
P = np.array([
    (1, 1, 0),
    (0, 1, 0),
    (0, 0, 1)
])

In [48]:
# Стандартный способ применить вращение к набору координат
R.apply(P)

array([[ 0., -1.,  1.],
       [ 0., -1.,  0.],
       [ 1.,  0.,  0.]])

In [49]:
# альтернативный сапособ применить вращения
R.as_matrix() @ P.T

array([[ 0.,  0.,  1.],
       [-1., -1.,  0.],
       [ 1.,  0.,  0.]])

### Пример вращения с помощью кватерниона из презентации

In [76]:
# Поворот на угол π/3
R2 = Rotation.from_quat([0, 0, sin(pi/6), cos(pi/6)])

In [77]:
R2.as_euler(seq='XYZ', degrees=True)

array([-0.,  0., 60.])

In [78]:
R2.apply([1, 0, 0])

array([0.5      , 0.8660254, 0.       ])

In [79]:
np.rad2deg(R2.magnitude())

59.99999999999999

In [80]:
R2.as_rotvec() / R2.magnitude()

array([0., 0., 1.])