In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from ipywidgets import interact
import math
import ipywidgets as widgets
#from mpl_toolkits.mplot3d.art3d import Poly3DCollection
#from scipy.spatial.transform import Rotation as R
#import quaternion
#import matplotlib as mpl

In [3]:
def task1(ra,rb):
  xyz = np.array([[1,0,1,1],
                [-1,0,1,1],
                [-1,0,-1,1],
                [1,0,-1,1],
                [0,2,0,1]
                    ])
  faces = [#[2,3,0,1],
          [0,4,1],
          [1,4,2],
          [2,4,3],
          [3,4,0]]

  a = np.radians(ra)
  b = np.radians(rb)
  rbra = np.array([[np.cos(a),0,np.sin(a),0],
                [np.sin(a)*np.sin(b),np.cos(b),-np.sin(b)*np.cos(a),0],
                 [-np.sin(a)*np.cos(b),np.sin(b),np.cos(a)*np.cos(b),0],
                  [0,0,0,1]])

  XYZ = xyz @ rbra.T

  Pxy= np.array([[1,0,0,0],
                [0,1,0,0],
                [0,0,0,0],
                [0,0,0,1]])
  M = Pxy @ rbra @ np.eye(4)
  XYZ1=XYZ[:,:2]
  ex = M[:3,:1]
  ey = M[:3,1:2]
  ez = M[:3,2:3]
  fx = np.sqrt(np.cos(a)**2+(np.sin(a)**2)*(np.sin(b)**2))
  fy = np.sqrt(np.cos(b)**2)
  fz = np.sqrt(np.sin(a)**2+(np.sin(b)**2)*(np.cos(a)**2))
  print(ex,fy,fz)
  fig01 = plt.figure(num=1,dpi=200)
  ax01 = fig01.add_subplot(1,1,1)
  ax01.grid(ls='--',lw=0.5,color='lightgrey')
  ax01.set_aspect('equal')
  ax01.set_xlim(-3, 3)
  ax01.set_ylim(-3, 3)
  #ax01.scatter(*XYZ1[2])
  #print(XYZ1[[0,4,1]][1])
  ax01.plot([0,10*ex[0][0]],[0,10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,-10*ex[0][0]],[0,-10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,10*ey[0][0]],[0,10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,-10*ey[0][0]],[0,-10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,10*ez[0][0]],[0,10*ez[1][0]],color='b',lw=0.5)
  ax01.plot([0,-10*ez[0][0]],[0,-10*ez[1][0]],color='b',lw=0.5)
  #ax01.arrow(0,0,ex[0][0],ex[1][0],color="r")
  #ax01.arrow(0,0,*Y1[:2],color="g")
  #ax01.arrow(0,0,*Z1[:2],color="b")
  #ax01.quiver(-3,0,*X1[:2],color="r")
  for i in faces:
    os = 0.5*np.linalg.det(np.array([[XYZ1[i][0][0],XYZ1[i][1][0],XYZ1[i][2][0]],
                                 [XYZ1[i][0][1],XYZ1[i][1][1],XYZ1[i][2][1]],
                                    [1,1,1]]))
    if os>=0 or len(i)==4:
      T = mpatches.Polygon(XYZ1[i],fill=False)
    else:
      T = mpatches.Polygon(XYZ1[i],fill=False,ls='--',lw=0.5)
    ax01.add_patch(T)
interact(task1,ra=(0,180,1),rb=(0,180,1))

interactive(children=(IntSlider(value=90, description='ra', max=180), IntSlider(value=90, description='rb', ma…

<function __main__.task1(ra, rb)>

In [ ]:
def task1_2(fz):
  b = np.arcsin(fz/np.sqrt(2))
  a = np.arcsin(fz/np.sqrt(2-fz**2))
  xyz = np.array([[1,0,1,1],
                [-1,0,1,1],
                [-1,0,-1,1],
                [1,0,-1,1],
                [0,2,0,1]
                    ])
  faces = [#[2,3,0,1],
          [0,4,1],
          [1,4,2],
          [2,4,3],
          [3,4,0]]

  #a = np.radians(ra)
  #b = np.radians(rb)
  rbra = np.array([[np.cos(a),0,np.sin(a),0],
                [np.sin(a)*np.sin(b),np.cos(b),-np.sin(b)*np.cos(a),0],
                 [-np.sin(a)*np.cos(b),np.sin(b),np.cos(a)*np.cos(b),0],
                  [0,0,0,1]])

  XYZ = xyz @ rbra.T

  Pxy= np.array([[1,0,0,0],
                [0,1,0,0],
                [0,0,0,0],
                [0,0,0,1]])
  M = Pxy @ rbra @ np.eye(4)
  XYZ1=XYZ[:,:2]
  ex = M[:3,:1]
  ey = M[:3,1:2]
  ez = M[:3,2:3]
  fx = np.sqrt(np.cos(a)**2+(np.sin(a)**2)*(np.sin(b)**2))
  fy = np.sqrt(np.cos(b)**2)
  fz = np.sqrt(np.sin(a)**2+(np.sin(b)**2)*(np.cos(a)**2))
  print(fx,fy,fz)
  fig01 = plt.figure(num=1,dpi=200)
  ax01 = fig01.add_subplot(1,1,1)
  ax01.grid(ls='--',lw=0.5,color='lightgrey')
  ax01.set_aspect('equal')
  ax01.set_xlim(-3, 3)
  ax01.set_ylim(-3, 3)
  #ax01.scatter(*XYZ1[2])
  #print(XYZ1[[0,4,1]][1])
  ax01.plot([0,10*ex[0][0]],[0,10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,-10*ex[0][0]],[0,-10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,10*ey[0][0]],[0,10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,-10*ey[0][0]],[0,-10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,10*ez[0][0]],[0,10*ez[1][0]],color='b',lw=0.5)
  ax01.plot([0,-10*ez[0][0]],[0,-10*ez[1][0]],color='b',lw=0.5)
  #ax01.arrow(0,0,ex[0][0],ex[1][0],color="r")
  #ax01.arrow(0,0,*Y1[:2],color="g")
  #ax01.arrow(0,0,*Z1[:2],color="b")
  #ax01.quiver(-3,0,*X1[:2],color="r")
  for i in faces:
    os = 0.5*np.linalg.det(np.array([[XYZ1[i][0][0],XYZ1[i][1][0],XYZ1[i][2][0]],
                                 [XYZ1[i][0][1],XYZ1[i][1][1],XYZ1[i][2][1]],
                                    [1,1,1]]))
    if os>=0 or len(i)==4:
      T = mpatches.Polygon(XYZ1[i],fill=False)
    else:
      T = mpatches.Polygon(XYZ1[i],fill=False,ls='--',lw=0.5)
    ax01.add_patch(T)
interact(task1_2,fz=(0,1,0.01))

interactive(children=(FloatSlider(value=0.0, description='fz', max=1.0, step=0.01), Output()), _dom_classes=('…

<function __main__.task1_2(fz)>

In [ ]:
def task1_3(v):
  if v == 1 :
    b = np.arcsin(1/np.sqrt(3))
    a = np.pi/4
  elif v == 2:
    b = -np.arcsin(1/np.sqrt(3))
    a = np.pi/4
  elif v == 3:
    b = np.arcsin(1/np.sqrt(3))
    a = -np.pi/4
  elif v == 4:
    b = -np.arcsin(1/np.sqrt(3))
    a = -np.pi/4
  xyz = np.array([[1,0,1,1],
                [-1,0,1,1],
                [-1,0,-1,1],
                [1,0,-1,1],
                [0,2,0,1]
                    ])
  faces = [#[2,3,0,1],
          [0,4,1],
          [1,4,2],
          [2,4,3],
          [3,4,0]]

  #a = np.radians(ra)
  #b = np.radians(rb)
  rbra = np.array([[np.cos(a),0,np.sin(a),0],
                [np.sin(a)*np.sin(b),np.cos(b),-np.sin(b)*np.cos(a),0],
                 [-np.sin(a)*np.cos(b),np.sin(b),np.cos(a)*np.cos(b),0],
                  [0,0,0,1]])

  XYZ = xyz @ rbra.T

  Pxy= np.array([[1,0,0,0],
                [0,1,0,0],
                [0,0,0,0],
                [0,0,0,1]])
  M = Pxy @ rbra @ np.eye(4)
  XYZ1=XYZ[:,:2]
  ex = M[:3,:1]
  ey = M[:3,1:2]
  ez = M[:3,2:3]
  fx = np.sqrt(np.cos(a)**2+(np.sin(a)**2)*(np.sin(b)**2))
  fy = np.sqrt(np.cos(b)**2)
  fz = np.sqrt(np.sin(a)**2+(np.sin(b)**2)*(np.cos(a)**2))
  print(fx,fy,fz)
  fig01 = plt.figure(num=1,dpi=200)
  ax01 = fig01.add_subplot(1,1,1)
  ax01.grid(ls='--',lw=0.5,color='lightgrey')
  ax01.set_aspect('equal')
  ax01.set_xlim(-3, 3)
  ax01.set_ylim(-3, 3)
  #ax01.scatter(*XYZ1[2])
  #print(XYZ1[[0,4,1]][1])
  ax01.plot([0,10*ex[0][0]],[0,10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,-10*ex[0][0]],[0,-10*ex[1][0]],color='r',lw=0.5)
  ax01.plot([0,10*ey[0][0]],[0,10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,-10*ey[0][0]],[0,-10*ey[1][0]],color='g',lw=0.5)
  ax01.plot([0,10*ez[0][0]],[0,10*ez[1][0]],color='b',lw=0.5)
  ax01.plot([0,-10*ez[0][0]],[0,-10*ez[1][0]],color='b',lw=0.5)
  #ax01.arrow(0,0,ex[0][0],ex[1][0],color="r")
  #ax01.arrow(0,0,*Y1[:2],color="g")
  #ax01.arrow(0,0,*Z1[:2],color="b")
  #ax01.quiver(-3,0,*X1[:2],color="r")
  for i in faces:
    os = 0.5*np.linalg.det(np.array([[XYZ1[i][0][0],XYZ1[i][1][0],XYZ1[i][2][0]],
                                 [XYZ1[i][0][1],XYZ1[i][1][1],XYZ1[i][2][1]],
                                    [1,1,1]]))
    if os>=0 or len(i)==4:
      T = mpatches.Polygon(XYZ1[i],fill=False)
    else:
      T = mpatches.Polygon(XYZ1[i],fill=False,ls='--',lw=0.5)
    ax01.add_patch(T)
w=widgets.Dropdown(options=[('a>0,b>0',1),('a>0,b<0',2),('a<0,b>0',3),('a<0,b<0',4)])
interact(task1_3,v=w)

interactive(children=(Dropdown(description='v', options=(('a>0,b>0', 1), ('a>0,b<0', 2), ('a<0,b>0', 3), ('a<0…

<function __main__.task1_3(v)>

In [ ]:
def task2(y=0,x=0,z=0):

  xyz = np.array([[1+x,0+y,1+z,1],
                [-1+x,+y,1+z,1],
                [-1+x,0+y,-1+z,1],
                [1+x,0+y,-1+z,1],
                [0+x,2+y,z,1]
                    ])
  faces = [#[2,3,0,1],
          [0,4,1],
          [1,4,2],
          [2,4,3],
          [3,4,0]]
  face = [0,1,2,3]

  b = np.arcsin(1/np.sqrt(3))
  a = np.pi/4
  rbra = np.array([[np.cos(a),0,np.sin(a),0],
                [np.sin(a)*np.sin(b),np.cos(b),-np.sin(b)*np.cos(a),0],
                 [-np.sin(a)*np.cos(b),np.sin(b),np.cos(a)*np.cos(b),0],
                  [0,0,0,1]])

  M = rbra @ np.eye(4)
  XYZ = xyz @ rbra.T
  XYZ1=XYZ[:,:2]

  #print(ST)
  ex = M[:3,:1]
  ey = M[:3,1:2]
  ez = M[:3,2:3]
  fig02 = plt.figure(num=1,dpi=200)
  ax02 = fig02.add_subplot(1,1,1)
  #ax02.grid(ls='--',lw=0.5,color='lightgrey')
  ax02.set_aspect('equal')
  ax02.set_xlim(-1, 14)
  ax02.set_ylim(-6, 6)
  ax02.plot([0,100*ex[0][0]],[0,100*ex[1][0]],color='r',lw=0.5)
  ax02.plot([0,-100*ex[0][0]],[0,-100*ex[1][0]],color='r',lw=0.5)
  ax02.plot([0,100*ey[0][0]],[0,100*ey[1][0]],color='g',lw=0.5)
  ax02.plot([0,-100*ey[0][0]],[0,-100*ey[1][0]],color='g',lw=0.5)
  ax02.plot([0,100*ez[0][0]],[0,100*ez[1][0]],color='b',lw=0.5)
  ax02.plot([0,-100*ez[0][0]],[0,-100*ez[1][0]],color='b',lw=0.5)
  for i in range(0,12):
    for j in range(0,12):
      s = np.array([[i,0,j,1],
                [i+1,0,j,1],
                [1+i,0,1+j,1],
                [i,0,1+j,1]])
      S = s @ rbra.T
      S1 = S[:,:2]
      if (i+j)%2==0:
        L = mpatches.Polygon(S1[face],fill=True,color='r')
      else:
        L = mpatches.Polygon(S1[face],fill=True,color='b')
      ax02.add_patch(L)
  for i in faces:
    os = 0.5*np.linalg.det(np.array([[XYZ1[i][0][0],XYZ1[i][1][0],XYZ1[i][2][0]],
                                 [XYZ1[i][0][1],XYZ1[i][1][1],XYZ1[i][2][1]],
                                    [1,1,1]]))
    if os>=0 or len(i)==4:
      T = mpatches.Polygon(XYZ1[i],fill=True)
    ax02.add_patch(T)
interact(task2,y=(0,14,0.1),x=(0,14,0.1),z=(0,14,0.1))

interactive(children=(FloatSlider(value=0.0, description='y', max=14.0), FloatSlider(value=0.0, description='x…

<function __main__.task2(y=0, x=0, z=0)>

In [ ]:
def task3(t,x=0,z=0,x1=0,z1=0,x2=0,z2=0):
  rad = np.radians(t)
  a = np.array([0,2,0]) / 2 #np.sqrt(x**2+4+z**2)
  la0 = np.cos(rad/2)
  la = (np.sin(rad/2) * a)

  cube = np.array([[0+x1,0,0+z1,1],
                    [0+x1,1,0+z1,1],
                    [1+x1,1,0+z1,1],
                    [1+x1,0,0+z1,1],
                    [0+x1,0,1+z1,1],
                    [0+x1,1,1+z1,1],
                    [1+x1,1,1+z1,1],
                    [1+x1,0,1+z1,1]
                    ])
  par = np.array([
    [0+x2, 0, 0+z2, 1], # 0
    [0+x2, 0, 1+z2, 1], # 1
    [3+x2, 0, 1+z2, 1], # 2
    [3+x2, 2, 1+z2, 1], # 3
    [0+x2, 2, 1+z2, 1], # 4
    [3+x2, 0, 0+z2, 1], # 5
    [3+x2, 2, 0+z2, 1], # 6
    [0+x2, 2, 0+z2, 1], # 7
    ])
  faces1 = np.array([[0,1,2,3],
                       [4,5,6,7],
                       [0,1,5,4],
                       [2,3,7,6],
                       [1,2,6,5],
                       [0,3,7,4]
                      ])
  xyz = np.array([[1+x,0,1+z,1],
                [-1+x,0,1+z,1],
                [-1+x,0,-1+z,1],
                [1+x,0,-1+z,1],
                [0+x,2,0+z,1]
                    ])
  xyz1 = xyz[:,:3] - np.array([x,0,z])
  P = xyz1 + ((2*la0)*np.cross(la,xyz1))+2*np.cross(la,np.cross(la,xyz1))
  P+=np.array([x,0,z])
  xyz2 = np.array([[*P[0],1],
                   [*P[1],1],
                   [*P[2],1],
                   [*P[3],1],
                   [*P[4],1]])
  faces = [#[2,3,0,1],
          [0,4,1],
          [1,4,2],
          [2,4,3],
          [3,4,0]]
  face = [0,1,2,3]
  faces2 = np.array([
    [0, 7, 4, 1],
    [1, 0, 5, 2],
    [0, 7, 6, 5],
    [4, 7, 6, 3],
    [3, 2, 5, 6],
    [1, 2, 3, 4],
    ])

  b = np.arcsin(1/np.sqrt(3))
  a = np.pi/4
  rbra = np.array([[np.cos(a),0,np.sin(a),0],
                [np.sin(a)*np.sin(b),np.cos(b),-np.sin(b)*np.cos(a),0],
                 [-np.sin(a)*np.cos(b),np.sin(b),np.cos(a)*np.cos(b),0],
                  [0,0,0,1]])

  M = rbra @ np.eye(4)
  PAR = par @ rbra.T
  CUBE = cube @ rbra.T
  XYZ = xyz2 @ rbra.T
  XYZ1=XYZ[:,:2]
  CUBE1 = CUBE[:,:2]
  PAR1 = PAR[:,:2]
  #print(ST)
  ex = M[:3,:1]
  ey = M[:3,1:2]
  ez = M[:3,2:3]
  fig03 = plt.figure(num=1,dpi=200)
  ax03 = fig03.add_subplot(1,1,1)
  ax03.grid(ls='--',lw=0.5,color='lightgrey')
  ax03.set_aspect('equal')
  ax03.set_xlim(-1, 14)
  ax03.set_ylim(-6, 6)
  ax03.plot([0,100*ex[0][0]],[0,100*ex[1][0]],color='r',lw=0.5)
  ax03.plot([0,-100*ex[0][0]],[0,-100*ex[1][0]],color='r',lw=0.5)
  ax03.plot([0,100*ey[0][0]],[0,100*ey[1][0]],color='g',lw=0.5)
  ax03.plot([0,-100*ey[0][0]],[0,-100*ey[1][0]],color='g',lw=0.5)
  ax03.plot([0,100*ez[0][0]],[0,100*ez[1][0]],color='b',lw=0.5)
  ax03.plot([0,-100*ez[0][0]],[0,-100*ez[1][0]],color='b',lw=0.5)
  for i in range(0,12):
    for j in range(0,12):
      s = np.array([[i,0,j,1],
                [i+1,0,j,1],
                [1+i,0,1+j,1],
                [i,0,1+j,1]])
      S = s @ rbra.T
      S1 = S[:,:2]
      if (i+j)%2==0:
        L = mpatches.Polygon(S1[face],fill=True,color='r')
      else:
        L = mpatches.Polygon(S1[face],fill=True,color='b')
      ax03.add_patch(L)
  for i in faces:
    os = 0.5*np.linalg.det(np.array([[XYZ1[i][0][0],XYZ1[i][1][0],XYZ1[i][2][0]],
                                 [XYZ1[i][0][1],XYZ1[i][1][1],XYZ1[i][2][1]],
                                    [1,1,1]]))
    if os>=0 or len(i)==4:
      W = mpatches.Polygon(XYZ1[i],fill=True)
      ax03.add_patch(W)
  for i in faces1:
      C = mpatches.Polygon(CUBE1[i],fill=True, color='g')
      ax03.add_patch(C)
  for i in faces2:
    P = mpatches.Polygon(PAR1[i],fill=True, color='y')
    ax03.add_patch(P)
interact(task3,t=(0,360,1),x=(0,14,0.1),z=(0,14,0.1),x1=(0,14,0.1),z1=(0,14,0.1),x2=(0,14,0.1),z2=(0,14,0.1))

interactive(children=(IntSlider(value=180, description='t', max=360), FloatSlider(value=0.0, description='x', …

<function __main__.task3(t, x=0, z=0, x1=0, z1=0, x2=0, z2=0)>

In [ ]:
int_range = widgets.IntSlider()
output2 = widgets.Output()

display(int_range, output2)

def on_value_change(change):
    with output2:
        print(change['new'])

int_range.observe(on_value_change, names='value')

IntSlider(value=0)

Output()

In [ ]:
x = 0
z = 0
rad = np.radians(180)
a = np.array([x,2,z])
A = np.array([[0,-a[2],a[1]],[a[2],0,-a[0]],[-a[1],a[0],0]])
R = np.eye(3) + (np.sin(rad) * A) + ((1-np.cos(rad)) * (A @ A))
xyz = np.array([[1+x,0,1+z,1],
                [-1+x,0,1+z,1],
                [-1+x,0,-1+z,1],
                [1+x,0,-1+z,1],
                [0+x,2,z,1]
                    ])
xyz1 = xyz[:,:3] @ R.T
xyz2 = np.array([[*xyz1[0],1],
                   [*xyz1[1],1],
                   [*xyz1[2],1],
                   [*xyz1[3],1],
                   [*xyz1[4],1]])
print(xyz1)
print(xyz2)

[[-7.  0. -7.]
 [ 7.  0. -7.]
 [ 7.  0.  7.]
 [-7.  0.  7.]
 [ 0.  2.  0.]]
[[-7.  0. -7.  1.]
 [ 7.  0. -7.  1.]
 [ 7.  0.  7.  1.]
 [-7.  0.  7.  1.]
 [ 0.  2.  0.  1.]]
